### ISSUE TITLE
Add browser/device requirements

### ISSUE THREAD

**Issue by modulesio** [exokitxr/exokit-web-docs#4]
C.f.

https://github.com/exokitxr/exokit-web/issues/26
https://github.com/exokitxr/exokit-web/issues/27

Anything that comes out of those issues that requires a non-stock setup should be noted in our docs, at least for our _own_ posterity.

**Comment by modulesio** [comment]
#### Firefox

Enable `javascript.options.shared_memory` through `about:config`

**Comment by chrisplatorres** [comment]
added the above Firefox requirement in a "Browser Requirement" page: 2cd5d87

Can add per-device or other browsers as needed
![docsgetstCapture](https://user-images.githubusercontent.com/29695350/64385912-54ecee80-cffd-11e9-8b64-5000270dd801.PNG)

**Comment by chrisplatorres** [comment]
Added WebXR browser requirements for Chrome, since that is the [main browser supporting WebXR currently](https://caniuse.com/#feat=webxr). (there is also Oculus Browser, Firefox Reality, Supermedium?)

![browserreqCapture](https://user-images.githubusercontent.com/29695350/64398637-2ab22580-d02b-11e9-9f82-706d9629841b.PNG)

**Comment by chrisplatorres** [comment]
Flags required for chrome XR entry:
![Capture16](https://user-images.githubusercontent.com/29695350/64465985-f09d5e00-d0d4-11e9-918a-748e4bd8c6af.PNG)

**Comment by chrisplatorres** [comment]
Added all requirements for:

- Desktop
- Quest
- Android phone chrome
- Desktop Firefox HTC Vive/OpenVR VR
- Desktop Chrome HTC Vive/OpenVR VR

Will also need:
- [ ] iOS
- [ ] MacOS
- [ ] Oculus Desktop VR for FF / Chrome

**Comment by chrisplatorres** [comment]
All devices have now been tested and requirements have been added https://github.com/exokitxr/exokit-web/issues/27#issuecomment-530109017
