### ISSUE TITLE
Dangling logos

### ISSUE THREAD

**Issue by modulesio** [exokitxr/exokit-web-docs#6]
![Capture](https://user-images.githubusercontent.com/6926057/64403019-ea5fa100-d044-11e9-979f-0ae475a883b8.PNG)

Should remove these, since they're off-brand for Exokit.

**Comment by chrisplatorres** [comment]
Fixed.
![icoexobotCapture](https://user-images.githubusercontent.com/29695350/64656044-b9d88800-d3f3-11e9-8380-a5dec57b01a8.PNG)
